apiVersion: v1
kind: Service 
metadata:
  name: myapp1-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp1
    # this must match the matchLabels in the myapp1 deployment yaml
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
